update

diff --git a/.github/workflows/deploy-component.yaml b/.github/workflows/deploy-component.yaml
--- a/.github/workflows/deploy-component.yaml
+++ b/.github/workflows/deploy-component.yaml
@@ -62,10 +62,29 @@ jobs:
       - name: Terraform Plan
         id: tfplan
         run: |
-          bin/terraform.sh --action ${{ inputs.mode }} \
+          ACTION=$(if [[ "${{ inputs.mode }}" == "destroy" ]]; then echo "plan-destroy"; else echo "plan"; fi)
+          echo $ACTION
+          bin/terraform.sh --action "${ACTION}" \
             --project ${{ vars.PROJECT }} \
             --region ${{ vars.REGION }} \
             --component ${{ inputs.component }} \
             --environment ${{ vars.ENVIRONMENT }} \
             --group ${{ vars.GROUP }} \
             --build-id ${{ github.run_id }}
+
+      - name: Generate TF Plan View
+        id: tfplan-view
+        run: |
+          cd "components/${{ inputs.component }}"
+          component=${{ inputs.component }}
+          read component_name <<< "${component##*/}"
+          if [ -f "build/${component_name}_${{ github.run_id }}.tfplan" ]; then
+            echo "Getting plan for ${component_name}_${{ github.run_id }}.tfplan"
+          else
+            echo "ERROR: Build file not found"
+            exit 1
+          fi
+          echo "### Terraform Plan" >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          terraform show -no-color "build/${component_name}_${{ github.run_id }}.tfplan" >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
