update

diff --git a/.github/workflows/plan-component.yaml b/.github/workflows/plan-component.yaml
--- a/.github/workflows/plan-component.yaml
+++ b/.github/workflows/plan-component.yaml
@@ -43,7 +43,47 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-      - name: Test
+        with:
+          fetch-depth: 0
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3.0.0
+        with:
+          terraform_wrapper: false
+          terraform_version: 1.7.4
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-region: eu-west-2
+          role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/DeploymentExecution
+          role-session-name: DeploymentExecution
+          role-duration-seconds: 3600
+
+      - name: Terraform Plan
+        id: tfplan
         run: |
-          echo ${{ matrix.modules }}
-          ls components/${{ matrix.modules }}
+          bin/terraform.sh --action plan \
+            --project ${{ vars.PROJECT }} \
+            --region ${{ vars.REGION }} \
+            --component ${{ inputs.component }} \
+            --environment ${{ vars.ENVIRONMENT }} \
+            --group ${{ vars.GROUP }} \
+            --build-id ${{ github.run_id }}
+
+      - name: Generate TF Plan View
+        id: tfplan-view
+        run: |
+          cd "components/${{ inputs.component }}"
+          component=${{ inputs.component }}
+          read component_name <<< "${component##*/}"
+          if [ -f "build/${component_name}_${{ github.run_id }}.tfplan" ]; then
+            echo "Getting plan for ${component_name}_${{ github.run_id }}.tfplan"
+          else
+            echo "ERROR: Build file not found"
+            exit 1
+          fi
+          echo "### Terraform Plan" >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          terraform show -no-color "build/${component_name}_${{ github.run_id }}.tfplan" >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
